version: '3'

services:
  api:
    build:
      context: ./api
    ports:
      - 5051:5051
    depends_on:
      - 'db'
    environment:
      - PORT=5051
      - ALLOWED_ORIGINS=web
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
      - PGDATABASE=purchase_planner
  db:
    build: ./db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - budgeter-db-data:/var/lib/postgresql/data:delegated

volumes:
  budgeter-db-data: